[package]
name = "chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ordered-float = "4.1.1"
rand = "0.8.5"
smallvec = "1.11.2"

[profile.release]
opt-level = 3  # Maximum optimization
